### ISSUE TITLE
Suggested changes for next update

### ISSUE THREAD

**Issue by kylebunting** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#26]
Adding this in for review during the next update of this HOL.

1. Provision lab resources using an ARM template.
2. Create a configuration script for the SqlServer2008 VM to do the following:
    - Download and install DMA
    - Download the database files from <https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks2008r2>.
    - Extract the downloaded database files to `C:\AdventureWorksSample`.
3. Create a configuration script for the LabVM to do the following:
     - Download and install SSMA for Oracle from <https://download.microsoft.com/download/1/2/6/126B0BE5-7731-4070-9AB1-73828D419781/SSMAforOracle_8.4.0.msi>.
     - Download and install dbForge Fusion from <https://www.devart.com/dbforge/oracle/fusion/dbforgeoracle39vs17.exe>
     - Download the lab starter solution from <https://github.com/microsoft/MCW-Data-Platform-upgrade-and-migration/archive/master.zip>.
     - Extract the lab starter solution to `C:\handsonlab`.

**Comment by timahenning** [comment]
Suggested new MCW title:  Migrating Oracle to Azure Databases

**Comment by DawnmarieDesJardins** [comment]
Outdated, closing
