### ISSUE TITLE
Migrating Oracle to Azure PostgreSQL

### ISSUE THREAD

**Issue by Hrashid789** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#32]
I have a quick question regarding "Migrating Oracle to Azure PostgreSQL. "I am on step 24, "Creating a new migration project", it seems like the "create project only" is in public preview and requires approval. Can you please guide me on overcoming this?
![Migration](https://user-images.githubusercontent.com/59919959/90163449-c8b38180-dd9e-11ea-86f4-777d76563baf.jpg)

**Comment by DawnmarieDesJardins** [comment]
@timahenning
Please review & advise.

**Comment by Hrashid789** [comment]
I resolved the issue by selecting a premium tier vs. standard, and I can create a project. After adding the source details, I get an error, "No archive redo log file (*.arc) exists." Please see the screenshot and advise.
Thank You!!
![ErrorDetails](https://user-images.githubusercontent.com/59919959/90182690-0cb47f80-ddbb-11ea-8d6a-155eaa678b9e.jpg)
![archivedlog](https://user-images.githubusercontent.com/59919959/90182695-0de5ac80-ddbb-11ea-9cfc-4676f11cb9f4.jpg)

**Comment by timahenning** [comment]
Hi @Hrashid789,

There seems to be a missing comment regarding "No archive redo log file."  Also, the issue above is resolved by using the premium tier sku.  I have updated the HOL document with that note.  Can I close this issue now?

Tim

**Comment by Hrashid789** [comment]
Thank You Tim!
