### ISSUE TITLE
Getting an error for employee table when using DMS

### ISSUE THREAD

**Issue by Hrashid789** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#34]
For some reason, the number of employee tables are different from the oracle source db. Appreciate if you can please look into this.
Thanks

**Comment by timahenning** [comment]
Hi,

@Hrashid789  Can you provide more details?  What document are you referring to?  What section?

Thanks,

Tim

**Comment by Hrashid789** [comment]
In Oracle to Postgres HOL, I am referring to Task 2: Use Azure Database Migration Service to migrate table data -> Step 34. When I ran the migration, that is where I got an error for the employee table that it is different from the source db.

**Comment by BenWurthCB** [comment]
Hi @Hrashid789,

I was able to get through the Hands-On-Lab without any issue. Is there any other information you can provide? Are you sure that you selected the right target schema and that the tables all matched up correctly?

Best,
Ben

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  PR #35 adds warning note regarding employee table error.
