### ISSUE TITLE
HOL step-by-step - Migrating Oracle to PostgreSQL

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#36]
In Exercise 3 Task4 ,we are asked to download **installora2pg.ps1** file using the URL provided in the task. But, the URL does not download the **installora2pg.ps1** script file. Instead the URL just navigates to the **installora2pg.ps1** file in browser.
https://github.com/microsoft/DataMigrationTeam/blob/master/IP%20and%20Scripts/PostgreSQL%20Migration%20and%20Assessment%20Tools/installora2pg.ps1
The file has been  downloaded manually and executed. As per the instruction in Exercise 3 Task4 step6, after executing **installora2pg.ps1** the oci.dll file is located under C:\instantclient_12_2\oci.dll.
In Exercise 3 Task 6, when step1 was performed I got to know that **ora2pg** directory does not exists.

**Comment by BenWurthCB** [comment]
Hi tejaswini972,

In response to the first part of your issue, I've submitted a pull request that changes the URL from the file's GitHub page to the raw file.

As for the second part of your issue, I was able to follow the instructions to the step you identified without any issues. This is a screenshot of the output I received after running installora2pg: 
![Screenshot_31](https://user-images.githubusercontent.com/29285196/94873188-64f31f80-0403-11eb-8cce-94bb0a63e38c.png)

Is it possible that you extracted the Oracle client library and SDK to the wrong place? They both need to be extracted to C:\

Let me know if you can provide me with any other clarifying details about your issue.

**Comment by tejaswini972** [comment]
Hi @BenWurthCB,
Even I was getting the same output as per the screenshot. Also, I have extracted the Oracle client library and SDK to the same path as specified in the lab guide (i.e, C:\\). 
In Exercise 3 Task 6, when step1 was performed, the output said **ora2pg** directory does not exists.

**Comment by BenWurthCB** [comment]
Hi @tejaswini972,

This is expected behavior. The script installs files to that directory and creates the directory if it does not exist. Check the `C:\ora2pg` directory after the script runs to make sure that the files are installed: 
![Screenshot_34](https://user-images.githubusercontent.com/29285196/95473670-2f858f00-0939-11eb-93ff-70d70e4cb338.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved, issue is expected behavior.
