### ISSUE TITLE
HOL step-by-step - Migrating Oracle to Azure SQL

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#37]
In Exercise 4 Task6, while building the **NorthwindMVC** solution the build got failed and giving me this below error.

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. 
 For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.3.1.0-beta1-final\build\Microsoft.Net.Compilers.props.

I followed the above link mentioned in the error to rectify the issue. Even though, the **Package restore** has been enabled and all the packages are up-to-date. Still the build got failed. Please, find the below screenshot for reference.

![Screenshot (11)](https://user-images.githubusercontent.com/52440474/94268720-38e72280-ff5b-11ea-9033-1b23c14d1c3c.png)

Thanks and Regards,
Tejaswini.

**Comment by timahenning** [comment]
Trying running the NuGet Package Restore from the Solution Explorer menu.

![image](https://user-images.githubusercontent.com/48766586/94272410-e1639b00-fef7-11ea-835b-5ed075888be1.png)

**Comment by tejaswini972** [comment]
I tried that, but still the build is failing and giving me the same error.

**Comment by timahenning** [comment]
Do you have all of the correct .NET Frameworks installed?

Try `dotnet restore --force`

![image](https://user-images.githubusercontent.com/48766586/94290481-16c7b300-ff0f-11ea-8304-284a08ef1b4f.png)

**Comment by tejaswini972** [comment]
Yes, I do have the correct .Net Frameworks installed.
I tried this also **dotnet restore --force** .
It says this..

![Screenshot (22)](https://user-images.githubusercontent.com/52440474/94407346-f9a21700-0190-11eb-9f52-2cb707af9b9c.png)

And all the packages are installed.

![Screenshot (23)](https://user-images.githubusercontent.com/52440474/94407744-7634f580-0191-11eb-875d-884a343a367e.png)

Still the build is failing and giving me the same error.

**Comment by akn9050** [comment]
Hi All, any update on this

**Comment by BenWurthCB** [comment]
Hi, @tejaswini972,

I was able to build the solution without any problems after following the instructions in the Hands-on-lab. Here is a screenshot of my build for reference: 
![Screenshot_32](https://user-images.githubusercontent.com/29285196/95114080-3a051600-06f8-11eb-8c64-5113845df901.png)
 
Do you have any other clarifying details about your issue you could share?

**Comment by BenWurthCB** [comment]
Hi, @tejaswini972,

The issue you encountered was caused by a mismatch in the declared version for the Microsoft.Net.Compilers package between `NorthwindMVC.csproj` and `packages.config`. I've submitted PR #39 which will resolve this issue, but you can also fix it in your current environment by going to `NorthwindMVC.csproj` and changing line 4 to be: 
``` csproj
<Import Project="..\packages\Microsoft.Net.Compilers.3.6.0\build\Microsoft.Net.Compilers.props" Condition="Exists('..\packages\Microsoft.Net.Compilers.3.6.0\build\Microsoft.Net.Compilers.props')" />
```
and changing line 1030 to be:
``` csproj
<Error Condition="!Exists('..\packages\Microsoft.Net.Compilers.3.6.0\build\Microsoft.Net.Compilers.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Net.Compilers.3.6.0\build\Microsoft.Net.Compilers.props'))" />
```
