### ISSUE TITLE
Azure Database HOL

### ISSUE THREAD

**Issue by ctgunawan** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#4]
It's said in HOL Abstract and Learning Objectives that we will "Implement high availability using Stretch Database and AlwaysOn Availability Groups" but there's no lab to implement this. Can we add one more exercise to cater this requirement?

**Comment by kylebunting** [comment]
@ctgunawan, the abstract has been updated in the june-2018-update branch to remove the reference to Stretch Database and AlwaysOn Availability Groups in the HOL abstract.

This lab is already right at the maximum amount of time allowable for these workshops, so adding another exercise to cater to this requirement will be difficult. However, if we were to use an ARM template to provision the lab VMs, and handle installing the SQL Server instances, we may be able to reduce the time required for Exercise 1, and free up some time for this.

I'm going to leave this issue open for consideration with the next update.
