### ISSUE TITLE
PostgreSQL: Exercise 3: Task 6: ora2pg not found

### ISSUE THREAD

**Issue by SeeratArora23** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#42]
[Exercise 3: Task 6:](https://github.com/microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Migrating%20Oracle%20to%20PostgreSQL.md#task-6-create-an-ora2pg-project-structure) On executing command **cd C:\ora2pg**, it says directory not found.

Can we please have this reviewed?

Thanks

**Comment by timahenning** [comment]
Hi @SeeratArora23,

Thank you for your issue submission.  We will review the issue within 5 - 10 business days.

**Comment by saimachi** [comment]
Hello @SeeratArora23,

Thank you for notifying us of this error. I was unable to encounter the same error in my environment. I could navigate to the `c:\ora2pg` directory and create a new project structure:

![image](https://user-images.githubusercontent.com/37318129/125396389-5312b580-e361-11eb-9b89-36ffb32a3c8e.png)

The most likely cause of the error in your environment is that the `installora2pg.ps1` script failed. Could you post the output of executing this PowerShell script so we can help you debug? The script will install Perl, Git, and other dependencies. It requires you to manually download the Oracle Client Library, however.

I have also confirmed that the ora2pg script requires the Oracle Client Library and SDK to be located in `c:\instantclient`, not `c:\instantclient_12_2`. Try renaming the directory and running the script again.
