### ISSUE TITLE
Sept 2021 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#43]

**Comment by joelhulen** [comment]
Pre-HOL:

* Add an ARM template to the Pre-HOL.
  * Create separate templates for the Oracle to Azure SQL and Oracle to PostgreSQL migration paths or a nested template that lets the user select the deployment option.

Oracle to Azure SQL:

* Update the sample application from ASP.NET MVC (.NET Framework) to ASP.NET Core 5.0 (.NET 5) MVC.
  * Clean up unused NuGet packages.
  * Add steps to update Visual Studio 2019 and install the dotnet SDK through the Visual Studio installer.
  * Update to use Entity Framework Core and a new Oracle provider NuGet package and steps for using the EF Core tools to generate models.
* Demonstrate administrative tasks through the portal for the SQL Server IaaS offering, including Azure Defender for SQL vulnerability assessment.

Oracle to PostgreSQL:

* Update the sample app, as described above.
* Remove the Devart commercial connector in favor of the open-source Npgsql EF Core provider. This will also avoid the strange licensing step in Exercise 4, Task 7.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #46
