### ISSUE TITLE
Unable to find a directory C:\ora2pg

### ISSUE THREAD

**Issue by Katelyn98098s** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#45]
Hello team,

I have followed all the steps until Task 6 of HOL step-by-step - Migrating Oracle to PostgreSQL.
I installed ora2pg in Task 4, but there is no directory "C:\ora2pg" that mentioned in Task 6> Step1.
Can anyone help me what should I check more ?
![image](https://user-images.githubusercontent.com/81273138/127832897-ded929f4-6536-4019-a41d-55dc8f72ef2d.png)

**Comment by saimachi** [comment]
Hey @Katelyn98098s,

Thanks for bringing this issue to our attention. This is similar to issue #42, so please review the resolution for that issue.

This lab is also undergoing a major update, so we'll clarify this further.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, as no further contact from field.
