### ISSUE TITLE
In the SSMA,SSMS and Portal, the IP address is not consistent.

### ISSUE THREAD

**Issue by nilabjaball** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#47]
when i look at the screenshots, under ssma section, in one i see localhost, 
in portal section ip address is 109.209.246.36 but in ssms 52.183.11.81 and in another 
either redact all the IPs and blur them or make it consistent

**Comment by timahenning** [comment]
Hi @nilabjaball, is this comment related to the PR?

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #43
