### ISSUE TITLE
Issue with the URL in Before the HOL

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#53]
1. In [Task-9](https://github.com/microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Migrating%20Oracle%20to%20Azure%20SQL%20and%20PostgreSQL.md#task-9-migrate-to-postgresql-install-the-ora2pg-utility), it is mentioned to use the URL https://raw.githubusercontent.com/microsoft/DataMigrationTeam/master/IP%20and%20Scripts/PostgreSQL%20Migration%20and%20Assessment%20Tools/installora2pg.ps1 to download **installora2pg.ps1** script. But it is throwing the error **400: Invalid request.**

**Comment by saimachi** [comment]
Hi @Divyasri199,

Thanks for bringing this issue to our attention. It looks like the `installora2pg.ps1` script is no longer accessible at that location.

On my [fork](https://github.com/saimachi/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL), I have added the script to the repository so you no longer need to download it. Try following the directions on my fork to install the tool and let me know if the install works as expected so I can merge the changes.
