### ISSUE TITLE
Issue in Migrating Oracle to PostgreSQL Exercise 4, task 3

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#57]
In [Exercise 4, Task 3, step 4](https://github.com/microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Migrating%20Oracle%20to%20PostgreSQL.md#task-3-finishing-the-table-schema-migration), after migrating table data to the PostgreSQL instance successfully using ora2pg utility, I am not able to see the data in PgAdmin after running the query inside the editor.

As shown in the below screenshot, the query is running successfully but the data is not loaded.

![image](https://user-images.githubusercontent.com/83349665/148449691-e4c2074e-251a-440a-b1f5-c8ae805dc716.png)

**Comment by sumitmalik51** [comment]
Hey @saimachi , We are revalidating the lab again today and will give you an update regarding this. Thanks

**Comment by Kalyani7744** [comment]
Closing the issue as the issue is resolved.
