### ISSUE TITLE
Before hands on lab: Task 9, Install ora2pg is failing randomly 

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#59]
HI,

The Installora2pg script is failing randomly, in some cases its working fine in some its not, 
find the attached file for the logs.
[](url
[ora2pglogs.txt](https://github.com/microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/files/7916157/ora2pglogs.txt)
)

**Comment by timahenning** [comment]
Hi @sumitmalik51,

I was able to run the script without issue.  Did you retry the script again? Can you confirm the server had Internet access?

Thanks!

**Comment by sumitmalik51** [comment]
Hi @timahenning , yes the server have internet connection, also i ran the same script 4 to 5 times and it worked under the same server

Thanks
