### ISSUE TITLE
Issue while installing postgres NuGet package.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#61]
Hi,

Facing the below issue while installing and updating the NuGet packages,
![image](https://user-images.githubusercontent.com/45102602/150825558-068fcbfd-3bc9-4780-9b9e-3ed5c8e5c47f.png)

Able to resolve it after updating the version in NorthwindMVC.csproj target .net version file

**Comment by saimachi** [comment]
Hi @sumitmalik51,

In my recent update of the lab, I already added the correct version of the Npgsql connector to the `.csproj` file. Please pull my latest changes and let me know if the issue persists.

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 
Hello!  Per Sai's comment, can I close this issue?  Thanks!

**Comment by sumitmalik51** [comment]
Yes, Please close, I was able to complete the lab without any issues. Thanks
