### ISSUE TITLE
Issue in Dashboard launch in browser in Exercise1>Task2>Step8.

### ISSUE THREAD

**Issue by ShivaUdari** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#63]
Encountered issue in Dashboard launch in browser in Exercise1>Task2>Step8 stating "_InvalidOperationException: The view 'Index' was not found_". PFB screenshot FYR.

![image](https://user-images.githubusercontent.com/58033932/151260069-3c582f1e-c504-48d3-b729-f287f965d6e5.png)

**Comment by saimachi** [comment]
Hi @ShivaUdari,

I did not encounter this error. The view displayed as expected. 

Did you make any changes to the application, such as unintentionally deleting `Index.cshtml`? You could also try downloading the lab files again, as explained in Task 1, Step 1.

**Comment by DawnmarieDesJardins** [comment]
@ShivaUdari 
Hello!  Were you able to move forward with the advice above?

**Comment by ShivaUdari** [comment]
Hello @saimachi & @DawnmarieDesJardins,

Thanks you for looking into his and regret the delayed response!

We are good to close the issue.

Thanks again and Have a great day!
